"""Adds initial_owner column.

Revision ID: 29730dad55b3
Revises: 
Create Date: 2023-07-25 02:28:49.302692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29730dad55b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_owner', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_column('initial_owner')

    # ### end Alembic commands ###
